---
title: "Untitled"
format: html
---


```{r}
library(episomer)
library(dplyr)
setup_config()
date_min <- substr(as.character(Sys.Date() - 10), 1, 10)
date_max <- substr(as.character(Sys.Date()), 1, 10)
```

```{r}
df <- tibble::tibble(episomer::search_posts(topic = "covid-19"))
# voir parametre query: format Lucene avec OR/AND etc ...
df
```

# Exploration get_aggregates

## 1. country_counts

```{r, eval=FALSE}
country_counts <- get_aggregates("country_counts",
    filter = list(period = c(date_min, date_max)), cache = FALSE
) %>%
    as_tibble()
```

## 2. geolocated

```{r, eval=FALSE}
geolocated <- get_aggregates("geolocated",
    filter = list(period = c(date_min, date_max)), cache = FALSE
) %>%
    as_tibble()
```

## 3. tags

```{r, eval=FALSE}
tags <- get_aggregates("tags",
    filter = list(period = c(date_min, date_max)), cache = FALSE
) %>%
    as_tibble()
```

## 4. topwords

```{r, eval=FALSE}
topwords <- get_aggregates("topwords",
    filter = list(period = c(date_min, date_max)), cache = FALSE
) %>%
    as_tibble()
```

## 5. urls

```{r, eval=FALSE}
urls <- get_aggregates("urls",
    filter = list(period = c(date_min, date_max)), cache = FALSE
) %>%
    as_tibble()
```

## 6. posts

```{r, eval=FALSE}
posts <- get_aggregates("posts",
    filter = list(period = c(date_min, date_max)), cache = FALSE
) %>%
    as_tibble()
```

```{r}
# saveRDS(
#     list(
#         country_counts = country_counts,
#         geolocated = geolocated,
#         tags = tags,
#         topwords = topwords,
#         urls = urls,
#         posts = posts
#     ),
#     file = file.path(
#         system.file("get_aggregates_explo", package = "episomer"),
#         "get_aggregates_sample.rds"
#     )
# )
```

```{r}
get_aggregates_sample <- readRDS(file.path(system.file("get_aggregates_explo", package = "episomer"), "get_aggregates_sample.rds"))
```

```{r}
View(get_aggregates_sample$country_counts)
```

# trend_line


```{r}
topic = "Measles"
countries = c(1)
date_type = "created_date"
date_min = "2025-08-01"
date_max = Sys.Date()

location_type = "post"
alpha = 0.025
alpha_outlier = 0.05
k_decay = 4
no_historic = 7
bonferroni_correction = FALSE
same_weekday_baseline = FALSE 

with_quotes = TRUE
setup_config()
trend_no_countries <- trend_line(
    topic = topic,
    countries = countries,
    date_type = date_type,
    date_min = date_min,
    date_max = date_max,
    with_quotes = with_quotes,
    alpha = alpha,
    alpha_outlier = alpha_outlier,
    k_decay = k_decay,
    no_historic = no_historic,
    bonferroni_correction = bonferroni_correction,
    same_weekday_baseline = same_weekday_baseline
)
trend_no_countries

trend_countries <- trend_line(
    topic = topic,
    countries = 4,
    date_type = date_type,
    date_min = date_min,
    date_max = date_max,
    with_quotes = with_quotes,
    alpha = alpha,
    alpha_outlier = alpha_outlier,
    k_decay = k_decay,
    no_historic = no_historic,
    bonferroni_correction = bonferroni_correction,
    same_weekday_baseline = same_weekday_baseline
)
trend_countries
```

# create_topchart

```{r}
setup_config()
#debugonce(create_topchart)

# TEST OK avec topwords
topch1 <- create_topchart(topic = topic, serie = "topwords", country_codes=c(),date_min=date_min,date_max=date_max, with_quotes = FALSE, top = 25)

topch1r <- create_topchart(topic = topic, serie = "topwords", country_codes=c(),date_min=date_min,date_max=date_max, with_quotes = TRUE, top = 25)

# TEST OK avec tags
topch2 <- create_topchart(topic = topic, serie = "tags", country_codes=c(),date_min=date_min,date_max=date_max, with_quotes = FALSE, top = 25)

# TEST OK avec urls
topch3 <- create_topchart(topic = topic, serie = "urls", country_codes=c(),date_min=date_min,date_max=date_max, with_quotes = FALSE, top = 25)

# With countries
countries_top_chart <- c("AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", 
"DE", "GR",
 "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL",
"PT", "RO", "SK", "SI", "ES", "SE")
 topch4 <- create_topchart(topic = topic, serie = "topwords", country_codes=countries_top_chart,date_min=date_min,date_max=date_max, with_quotes = FALSE, top = 25)
```

# create_map

```{r}
setup_config()
m1 <- create_map(topic = topic, countries = countries, date_min = date_min, date_max = date_max, with_quotes = FALSE)

m1r <- create_map(topic = topic, countries = countries, date_min = date_min, date_max = date_max, with_quotes = TRUE)

# test with some countries
countries <- 4
m2 <- create_map(topic = topic, countries = countries, date_min = date_min, date_max = date_max, with_quotes = TRUE)

countries <- 12
m2 <- create_map(topic = topic, countries = countries, date_min = date_min, date_max = date_max, with_quotes = TRUE)

# test "detailed"
countries <- 276 #USA
m3 <- create_map(topic = topic, countries = countries, date_min = date_min, date_max = date_max, with_quotes = TRUE)

```

```{r}
# raw <- episomer::get_aggregates("country_counts", filter = list(period = c(substr(as.character(Sys.Date() - 360), 1, 10), substr(as.character(Sys.Date()), 1, 10))), cache = F)

# agg <- tibble::tibble(
#     raw %>% dplyr::group_by(geo_country_code)
#         %>% dplyr::count() %>% dplyr::arrange(-n)
# )
# agg
# View(agg)
# original / quote : equivalent de original / repost
```


